package = "lualatex"
version = "0.3.11"
lua = ">=5.1"

[description]
summary = "lualatex for LaTeX"
maintainer = "Wu"
labels = ["texmf"]
detailed = "See https://github.com/ustctug/texrocks"
homepage = "https://www.lualatex.org/"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

# refer https://ctan.org/pkg/required
[dependencies]
texrocks = "0.3.11-1"
amsfonts = "3.04-1"
# tex-ini-files provide lualatexquotejobname.lua
tex-ini-files = "2025.02.09-1"
# latex-base depends on l3backend depends on unicode-data
latex-base = "2025.06.01-1"
luaotfload = "3.29-1"
lm = "2.005-1"

[build_dependencies]
texrocks = "0.3.11-1"
amsfonts = "3.04-1"
tex-ini-files = "2025.02.09-1"
latex-base = "2025.06.01-1"
latex-fonts = "0.0.1"

[run]
command = "lualatex"

[test]
type = "command"
command = "lualatex"
flags = ["test.tex"]

[deploy]
wrap_bin_scripts = false

[build]
type = "command"
build_command = "../initex/bin/initex --ini --interaction=nonstopmode lualatex.ini"

[build.install.bin]
lualatex = '../initex/bin/initex'

[build.install.conf]
'../web2c/luahbtex/lualatex.fmt' = 'lualatex.fmt'
