package = "lualatex"
version = "0.0.1"
lua = ">=5.1"

[description]
summary = "lualatex for LaTeX"
maintainer = "Wu"
labels = ["texmf"]
detailed = "See https://github.com/ustctug/texrocks"
homepage = "https://www.lualatex.org/"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/releases/download/0.0.1/empty.zip"
dir = "."

# refer https://ctan.org/pkg/required
[dependencies]
texrocks = "0.2.2-1"
amsfonts = "3.04-1"
# tex-ini-files provide lualatexquotejobname.lua
tex-ini-files = "2025.02.09-1"
# latex-base depends on l3backend depends on unicode-data
latex-base = "2024.11.01-2"

[build_dependencies]
texrocks = "0.2.2-1"
amsfonts = "3.04-1"
tex-ini-files = "2025.02.09-1"
latex-base = "2024.11.01-2"
latex-fonts = "0.0.1"

[run]
command = "lualatex"

[test]
type = "command"
command = "lualatex"
flags = ["test.tex"]

[deploy]
wrap_bin_scripts = false

[build]
type = "command"
build_command = "texlua --ini --interaction=nonstopmode lualatex.ini"

[build.install.bin]
lualatex = "lualatex"

[build.install.conf]
'../web2c/luahbtex/lualatex.fmt' = 'lualatex.fmt'
