local M = {}
M.LUA_VERSION = _VERSION:gsub('[^ ]* ', '')
M.fontmap_name = "luatex.map"

M.fontmap = string.gsub([[% generated by texrocks

%s

% ex: filetype=texmf
]], '%% ', '%%%% ')

M.wrapper = [[#!/usr/bin/env -S lx --lua-version=5.3 lua --lua=texlua --no-loader --
local args = {'%s'}
for _, v in ipairs(arg) do
    table.insert(args, v)
end
require 'texrocks.adapter'.run(args, false)
]]

return M
