local M = {}

M.fontmap = string.gsub([[% generated by texrocks

%s

% ex: filetype=texmf
]], '%% ', '%%%% ')

M.lx_wrapper = [[#!/usr/bin/env -S lx --lua-version=5.3 lua --lua=texlua --no-loader --
local args = {'initex', '--fmt=' .. '%s' .. '.fmt'}
for _, v in ipairs(arg) do
    table.insert(args, v)
end
require 'texrocks.adapter'.run(args, false)
]]

M.texlua_wrapper = [[#!/usr/bin/env texlua
    local args = {'initex', '--fmt=' .. '%s' .. '.fmt'}
    for _, v in ipairs(arg) do
        table.insert(args, v)
    end
    require 'texrocks.adapter'.run(args, false)
]]
M.LUA_VERSION = _VERSION:gsub('[^ ]* ', '')
M.fontmap_name = "luatex.map"

return M
