---
name: Deploy Action
description: A custom deploy action for the project
inputs:
  target:
    description: Deployment target
    required: true
  version:
    description: Lua version
    default: "5.3"
  skip:
    description: Skip deployment when rock is already on luarocks
    default: "true"
runs:
  using: composite
  steps:
    - run: |
        ${{ github.action_path }}/scripts/deploy.sh ${{ inputs.target }}
      shell: bash
      env:
        LUA_VERSION: ${{ inputs.version }}
        SKIP: ${{ inputs.skip }}
