package = "texluap"
version = "0.3.6"
lua = ">=5.1"

[description]
summary = "tlua: luatex as Lua interpreter, texlua's prompt"
detailed = "Refer https://github.com/mfussenegger/nlua"
maintainer = "Wu"
labels = [ "texmf" ]
homepage = "https://github.com/ustctug/texrocks"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
texrocks = "0.3.6-1"
prompt-style = "0.0.9-1"

[test_dependencies]
luatex = "0.3.6-1"

[run]
command = 'tlua'

[test]
type = 'command'
command = 'luatex'
flags = ['--shell-escape', 'test.tex']

[deploy]
wrap_bin_scripts = false

[build]
type = "builtin"

[build.install.bin]
tlua = "bin/tlua"
