package = "initex"
version = "0.3.10"
lua = ">=5.1"

[description]
summary = "An initial TeX without any extra features except generating other TeXs by `initex --ini XXX.ini`"
maintainer = "Wu"
labels = ["texmf"]
detailed = "See https://github.com/ustctug/texrocks"
homepage = "https://texrocks.readthedocs.io/en/latest/topics/initex.md.html"
license = "GPL-3.0"

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[build_dependencies]
texrocks = "0.3.10-1"

[dependencies]
texrocks = "0.3.10-1"

[run]
command = "initex"

[test]
type = "command"
command = "initex"
flags = ["test.tex"]

[deploy]
wrap_bin_scripts = false

[build]
type = "command"
build_command = "bin/initex --ini --interaction=nonstopmode initex.ini"

[build.install.bin]
initex = 'bin/initex'

[build.install.conf]
'../web2c/luahbtex/initex.fmt' = 'initex.fmt'
