package = "initex"
version = "0.0.1"
lua = ">=5.1"

[description]
summary = "initex"
maintainer = "Wu"
labels = ["texmf"]
detailed = "An initial TeX without any extra features except generating other TeXs by `initex --ini XXX.ini` and called by other TeXs by `initex --fmt XXX`"
homepage = "https://www.luatex.org/"
license = "GPL-3.0"

[source]
url = "https://github.com/ustctug/texrocks/releases/download/0.0.1/$(PACKAGE).ini.zip"
dir = "."

[dependencies]
texrocks = "0.2.1-1"

[build_dependencies]
texrocks = "0.2.1-1"

[run]
command = "initex"

[test]
type = "command"
command = "initex"
flags = ["test.tex"]

[deploy]
wrap_bin_scripts = false

[build]
type = "command"
build_command = "texlua --ini --interaction=nonstopmode initex.ini"

[build.install.bin]
initex = "initex"

[build.install.conf]
'../web2c/luahbtex/initex.fmt' = 'initex.fmt'
