package = "initex"
version = "0.3.2"
lua = ">=5.1"

[description]
summary = "initex"
maintainer = "Wu"
labels = ["texmf"]
detailed = "An initial TeX without any extra features except generating other TeXs by `initex --ini XXX.ini`"
homepage = "https://github.com/ustctug/texrocks"
license = "GPL-3.0"

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
texrocks = "0.3.2-1"

[run]
command = "initex"

[test]
type = "command"
command = "initex"
flags = ["test.tex"]

[deploy]
wrap_bin_scripts = false

[build]
type = "command"
build_command = "luahbtex --ini --interaction=nonstopmode initex.ini"

[build.install.bin]
initex = "bin/initex"

[build.install.conf]
'../web2c/luahbtex/initex.fmt' = 'initex.fmt'
