package = "luatexinfo"
version = "0.0.1"
lua = "==5.3"

[description]
summary = "LuaTeX for TeXinfo"
maintainer = "Wu Zhenyu"
labels = ["texmf"]
detailed = "See https://github.com/Freed-Wu/texrocks"
homepage = "https://www.luatex.org/"
license = 'GPL-3.0'

[source]
src = "https://github.com/ustctug/texrocks/releases/download/0.0.1/luatexinfo.zip"
dir = "."

[dependencies]
texrocks = "0.1.1-1"
texinfo = "7.2-2"
knuth-lib = "scm-1"
amsfonts = "scm-1"
tex-ini-files = "scm-1"

[test]
type = "command"
command = "texinfo"
# pdf has some bug about fonts' path
# args = ["main.texi"]
flags = ["--output-format=dvi", "main.texi"]

[deploy]
wrap_bin_scripts = false

[build]
type = "command"
build_command = "texlua build.lua luatexinfo"

[build.install.bin]
luatexinfo = "luatexinfo"
texinfo = "texinfo"

[build.install.conf]
'../web2c/luahbtex/luatexinfo.fmt' = 'luatexinfo.fmt'
