package = "luatexinfo"
version = "0.3.7"
lua = ">=5.1"

[description]
summary = "LuaTeX for TeXinfo"
maintainer = "Wu"
labels = ["texmf"]
detailed = "See https://github.com/ustctug/texrocks"
homepage = "https://www.luatex.org/"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[build_dependencies]
texrocks = "0.3.7-1"
amsfonts = "3.04-1"
tex-ini-files = "2025.02.09-1"
knuth-lib = "2021.02.05-1"
texinfo = "7.2-2"

[dependencies]
texrocks = "0.3.7-1"
amsfonts = "3.04-1"

[run]
command = "luatexinfo"

[test]
type = "command"
command = "luatexinfo"
flags = ["test.texi"]

[deploy]
wrap_bin_scripts = false

[build]
type = "command"
build_command = "../initex/bin/initex --ini --interaction=nonstopmode luatexinfo.ini"

[build.install.bin]
luatexinfo = '../initex/bin/initex'

[build.install.conf]
'../web2c/luahbtex/luatexinfo.fmt' = 'luatexinfo.fmt'
