package = "initex-plain"
version = "2025.02.09"
lua = "==5.3"

[description]
summary = "LuaTeX for plainTeX"
maintainer = "Wu Zhenyu"
labels = ["texmf"]
license = "GPL-3.0"

[dependencies]
texrocks = "==0.1.0"
amsfonts = "scm-1"
tex-ini-files = "scm-1"
unicode-data = "1.18-1"
# etex depends on knuth-lib
etex = "2.1-1"

[run]
command = "../../scripts/build.lua"
args = ["luatex", "zip"]

[build]
type = "none"
