package = "graph"
version = "scm-1"
lua = "==5.3"

[description]
summary = "Graph example for LaTeX"
maintainer = "Wu Zhenyu"
labels = ["texmf"]

[dependencies]
lualatex = "scm-1"
hologo = "scm-1"
standalone = "1.3-2"
pgf = "3.1.10-1"

[test]
type = "command"
command = "latex"
args = ["main.tex"]

[build]
type = "none"
