package = "lualatex-build-environment"
version = "0.0.1"
lua = "==5.3"

[description]
summary = "LuaTex for LaTeX"
maintainer = "Wu Zhenyu"
labels = ["texmf"]
license = "GPL-3.0"

[dependencies]
texrocks = "0.0.13-1"
amsfonts = "scm-1"
# refer https://ctan.org/pkg/required
# latex-base depends on l3backend depends on unicode-data
latex-base = "2024.11.01-2"
# tex-ini-files provide lualatexquotejobname.lua
tex-ini-files = "scm-1"
latex-fonts = "scm-1"

[run]
command = "texrocks"
args = ["dump", "lualatex"]

[build]
type = "none"
