package = "epstopdf"
version = "0.3.7"
lua = ">=5.1"

[description]
summary = "Convert EPS to PDF using Ghostscript"
detailed = "A reimplementation of https://ctan.org/pkg/epstopdf by texlua"
maintainer = "Wu"
labels = [ "texlua" ]
homepage = "https://github.com/ustctug/texrocks"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
texrocks = "0.3.7-1"
argparse = "0.7.1-1"

[deploy]
wrap_bin_scripts = false

[build]
type = "builtin"

[build.install.bin]
epstopdf = "0.3.7-1"
