package = "epstopdf"
version = "0.3.8"
lua = ">=5.1"

[description]
summary = "Convert EPS to PDF using Ghostscript"
detailed = "A reimplementation of https://ctan.org/pkg/epstopdf by texlua"
maintainer = "Wu"
labels = [ "texlua" ]
homepage = "https://texrocks.readthedocs.io/en/latest/topics/epstopdf.md.html"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
texrocks = "0.3.8-1"
argparse = "0.7.1-1"

[run]
command = "epstopdf"

[test]
type = "command"
command = "epstopdf"
flags = ["--debug", "--nogs", "test.eps"]

[deploy]
wrap_bin_scripts = false

[build]
type = "builtin"

[build.install.bin]
epstopdf = "0.3.8-1"

[test_dependencies]
l3build = "2024.10.16-1"
toml2lua = "3.0.0-1"
