package = "sdluatex"
version = "0.3.7"
lua = ">=5.1"

[description]
summary = "LuaTeX for sdLuaTeX"
maintainer = "Wu"
labels = ["texmf"]
detailed = "See https://github.com/ustctug/texrocks"
homepage = "https://www.speedata.de/"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
initex = "0.3.7-1"
publisher = "5.1.18-1"

[run]
command = "sdluatex"

[test]
type = "command"
command = "sdluatex"
flags = ["layout.xml", "data.xml"]

[deploy]
wrap_bin_scripts = false

[build]
type = "builtin"

[build.install.bin]
"sdluatex" = "bin/sdluatex"
