package = "demo-ieeetran"
version = "0.0.1"
lua = ">=5.1"

[description]
summary = "A Sample Article Using IEEEtran.cls for IEEE Journals and Transactions"
homepage = "https://template-selector.ieee.org/api/ieee-template-selector/template/12/download"
maintainer = "Michael Shell"
labels = ["Journal"]
license = "LPPL-1.3c"

[run]
type = "command"
command = "lx"
args = ["--tree=.lux", "doc", "demo-ieeetran"]

[build]
type = "command"
build_command = "llmk"

[build.install.conf]
"../doc/bare_jrnl_new_sample4.pdf" = "bare_jrnl_new_sample4.pdf"

[build_dependencies]
# lualatex
lualatex = ">=0.3.20"
# bibtex
bibtex = ">=0.99.5"
# llmk
light-latex-make = ">=1.2.0"
# \documentclass{IEEEtran}
ieeetran = ">=1.8.2"
# \usepackage{amsmath}
latex-amsmath = ">=2026.6.1"
# \usepackage{array}
# \usepackage{textcomp}
latex-tools = ">=2026.6.1"
# \usepackage{algorithm}
# \usepackage{algorithmic}
algorithms = ">=0.1"
# \usepackage{subfig}
subfig = ">=1.3"
# \includegraphics{fig1}
graphics-cfg = ">=0.0.1"
# \usepackage{stfloats}
sttools = ">=3.5"
# \usepackage{cite}
cite = ">=5.5"
# New_IEEEtran_how-to.tex
# \usepackage{balance}
preprint = ">=2011"
