package = "lua-open"
version = "0.2.4"
lua = ">=5.1"

[description]
summary = "Use system tool to open a file"
detailed = "If the file doesn't exist in current path, it will search package path by `lux.toml`"
maintainer = "Wu"
labels = ["texlua"]

[source]
url = "https://github.com/ustctug/texrocks/archive/5b3bc383b5fd6479e0377836f7c094e5a0ddb714.zip"
dir = "texrocks-5b3bc383b5fd6479e0377836f7c094e5a0ddb714/packages/$(PACKAGE)"
# url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
# dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
texrocks = "0.2.4-1"
toml2lua = "3.0.0-1"

[run]
command = "lua-open"

[deploy]
wrap_bin_scripts = false

[build]
type = "builtin"

[build.install.bin]
lua-open = 'bin/lua-open'
