package = "lua-open"
version = "0.3.4"
lua = ">=5.1"

[description]
summary = "Use system tool to open a file"
detailed = "If the file doesn't exist in current path, it will search package path by `lux.toml`"
maintainer = "Wu"
labels = ["texlua"]
homepage = "https://github.com/ustctug/texrocks"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
toml2lua = "3.0.0-1"
texrocks = "0.3.4-1"

[run]
command = "lua-open"

[test]
type = "command"
command = "lua-open"
flags = ["bin/lua-open"]

[deploy]
wrap_bin_scripts = false

[build]
type = "builtin"

[build.install.bin]
lua-open = 'bin/lua-open'
