package = "kpathsea"
version = "0.3.8"
lua = ">=5.1"

[description]
summary = "Standalone path lookup and expansion for the Kpathsea library"
detailed = "A reimplementation of https://tug.org/kpathsea's kpsewhich by texlua"
maintainer = "Wu"
labels = [ "texmf" ]
homepage = "https://github.com/ustctug/texrocks"
license = "GPL-3.0"

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[run]
command = 'kpsewhich'

[test]
type = 'command'
command = 'kpsewhich'
flags = ['url.sty']

[deploy]
wrap_bin_scripts = false

[dependencies]
texrocks = "0.3.8-1"
argparse = "0.7.1-1"
lua-semver = "1.2.2-1"

[test_dependencies]
lualatex = "0.3.8-1"

[build]
type = "builtin"

[build.install.bin]
kpsewhich = "bin/kpsewhich"
