package = "kpathsea"
version = "0.3.0"
lua = ">=5.1"

[description]
summary = "Standalone path lookup and expansion for the Kpathsea library"
detailed = "A reimplementation of <https://tug.org/kpathsea>'s kpsewhich by texlua"
maintainer = "Wu"
labels = [ "texmf" ]
license = "GPL-3.0"

[source]
# url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
# dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"
url = "https://github.com/ustctug/texrocks/archive/b8374b7c2935a56328af6c09a837b98987cc5673.zip"
dir = "texrocks-b8374b7c2935a56328af6c09a837b98987cc5673/packages/$(PACKAGE)"

[run]
command = 'kpsewhich'

[test]
type = 'command'
command = 'kpsewhich'
flags = ['texrocks.lua']

[deploy]
wrap_bin_scripts = false

[dependencies]
texrocks = "0.3.0-1"
argparse = "0.7.1-1"

[build]
type = "builtin"

[build.install.bin]
kpsewhich = "bin/kpsewhich"
