package = "demo"
version = "0.0.1"
lua = ">=5.1"

[description]
summary = "Example for LaTeX"
maintainer = "Wu"
labels = ["texmf"]

[build_dependencies]
lualatex = "0.0.1-1"
pgf = "3.1.10-1"
graphics-cfg = "0.0.1-1"
hyperref = "7.01-15"
hologo = "1.15-1"
standalone = "1.5-1"

[run]
type = "command"
command = "sh"
args = ["-c", "xdg-open .lux/5.3/*/etc/doc/main.pdf"]

[test]
type = "command"
command = "sh"
flags = ["-c", "pdftotext .lux/5.3/*/etc/doc/main.pdf -"]

[build]
type = "command"
build_command = "lualatex --interaction=nonstopmode main.tex"

[build.install.conf]
'../doc/main.pdf' = 'main.pdf'
