package = "demo"
version = "0.0.1"
lua = ">=5.1"

[description]
summary = "Example for LaTeX"
maintainer = "Wu"
labels = ["texmf"]

[dependencies]
lualatex = "0.0.1-1"
# hologo = "scm-1"
# standalone = "1.3-2"
# pgf = "3.1.10-1"

[run]
type = "command"
command = "lualatex"

[test]
type = "command"
command = "lualatex"
flags = ["main.tex"]

[build]
type = "none"
