package = "demo"
version = "0.0.1"
lua = ">=5.1"

[description]
summary = "Example for LaTeX"
maintainer = "Wu"
labels = ["texmf"]

[build_dependencies]

[run]
type = "command"
command = "lualatex"

[test]
type = "command"
command = "lualatex"
flags = ["main.tex"]

[build]
type = "command"
build_command = "lualatex --interaction=nonstopmode main.tex"

[build.install.conf]
'../doc/main.pdf' = 'main.pdf'
