package = "demo-tikz"
version = "0.0.1"
lua = ">=5.1"

[description]
summary = "Example for tikz"
maintainer = "Wu"
labels = ["texmf"]

[build_dependencies]
lualatex = "0.3.3-1"
pgf = "3.1.10-1"
graphics-cfg = "0.0.1-1"
hyperref = "7.01-15"
hologo = "1.15-1"
standalone = "1.5-1"

[test_dependencies]
lua-open = "0.3.3-1"

[test]
type = "command"
command = "lua-open"
flags = ["main.pdf"]

[build]
type = "command"
build_command = "lualatex --interaction=nonstopmode main.tex"

[build.install.conf]
'../doc/main.pdf' = 'main.pdf'
