package = "luarocks-build-l3build"
version = "0.0.1"
lua = ">=5.1"

[description]
summary = "Build lua rock file by l3build's build.lua"
detailed = "Make TeX ecosystem available for lua ecosystem"
maintainer = "Wu"
labels = ["texmf"]
homepage = "https://texrocks.readthedocs.io/en/latest/topics/luarocks-build-l3build.md.html"
license = 'GPL-3.0'

[source]
# url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
# dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"
url = "https://github.com/ustctug/texrocks/archive/bb2f102137b4b7b8a5b64c3a9c22ebbe20b317d8.zip"
dir = "texrocks-bb2f102137b4b7b8a5b64c3a9c22ebbe20b317d8/packages/$(PACKAGE)"

[dependencies]
luarocks = "3.12.2-1"
l3build = "2024.10.16-1"

[run]
command = "luarocks"

[test]
type = "command"
command = "luarocks"
flags = [
  "--lua-version=5.3",
  "--tree=.lux",
  "build",
  "--deps-mode=none",
  "../../rockspecs/hyperref-7.01-15.rockspec",
]

[build]
type = "builtin"

[test_dependencies]
luatex = "0.3.11-1"
latex-base = "2025.06.01-1"
