package = "luatex"
version = "scm"
lua = "==5.3"

[description]
summary = "LuaTeX for plainTeX"
maintainer = "Wu Zhenyu"
labels = ["texmf"]
detailed = "See https://github.com/Freed-Wu/texrocks"
homepage = "https://www.luatex.org/"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/releases/download/0.0.1/empty.zip"
dir = "."

[dependencies]
texrocks = "0.1.2-1"
amsfonts = "scm-1"

[build_dependencies]
texrocks = "0.1.2-1"
amsfonts = "scm-1"
tex-ini-files = "scm-1"
unicode-data = "1.18-1"
# etex depends on knuth-lib
etex = "2.1-1"

[run]
command = "texrocks"
args = ["luatex"]

[test]
type = "command"
command = "texrocks"
flags = ["luatex", "test.tex"]

[deploy]
wrap_bin_scripts = false

[build]
type = "command"
build_command = "texrocks --dump luatex"

[build.install.bin]
luatex = "luatex"
tex = "tex"

[build.install.conf]
'../web2c/luahbtex/luatex.fmt' = 'luatex.fmt'
