package = "luatex"
version = "0.0.1"
lua = "==5.3"

[description]
summary = "LuaTeX for plainTeX"
maintainer = "Wu Zhenyu"
labels = ["texmf"]
detailed = "See https://github.com/Freed-Wu/texrocks"
homepage = "https://www.luatex.org/"
license = 'GPL-3.0'

[source]
dev = "https://github.com/Freed-Wu/texrocks/releases/download/0.0.1/luatex.zip"
dir = "."

[dependencies]

[test]
type = "command"
command = "tex"
args = ["main.tex"]

[build]
type = "command"
build_command = "texlua ./build.lua luatex"

# https://github.com/nvim-neorocks/lux/issues/866
[build.install.bin]
luatex = "luatex"
tex = "tex"

[build.install.conf]
'../web2c/luahbtex/luatex.fmt' = 'luatex.fmt'

# https://github.com/nvim-neorocks/lux/issues/857
[deploy]
wrap_bin_scripts = false
