package = "luatex"
version = "0.0.1"
lua = ">=5.1"

[description]
summary = "LuaTeX for plainTeX"
maintainer = "Wu"
labels = ["texmf"]
detailed = "See https://github.com/ustctug/texrocks"
homepage = "https://www.luatex.org/"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/releases/download/0.0.1/empty.zip"
dir = "."

[dependencies]
texrocks = "0.2.1-1"
amsfonts = "3.04-1"

[build_dependencies]
texrocks = "0.2.1-1"
amsfonts = "3.04-1"
tex-ini-files = "2025.02.09-1"
unicode-data = "1.18-1"
# etex depends on knuth-lib
etex = "2.1-1"

[run]
command = "luatex"

[test]
type = "command"
command = "luatex"
flags = ["test.tex"]

[deploy]
wrap_bin_scripts = false

[build]
type = "command"
build_command = "texlua --ini --interaction=nonstopmode luatex.ini"

[build.install.bin]
luatex = "luatex"

[build.install.conf]
'../web2c/luahbtex/luatex.fmt' = 'luatex.fmt'
