package = "texdef"
version = "0.3.7"
lua = ">=5.1"

[description]
summary = "Show definitions of TeX commands"
detailed = "A reimplementation of https://github.com/MartinScharrer/texdef/ by texlua"
maintainer = "Wu"
labels = [ "texmf" ]
homepage = "https://github.com/ustctug/texrocks"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
argparse = "0.7.1-1"
lua-template = "1.0.0-1"
currfile = "1.0-1"
lualatex = "0.3.7-1"
luatex = "0.3.7-1"

[run]
type = "command"
command = "latexdef"

[test]
type = "command"
command = "texdef"
flags = ["TeX"]

[build]
type = "builtin"

[build.install.bin]
texdef = 'bin/texdef'
latexdef = 'bin/latexdef'
