package = "luarocks-build-autotools"
version = "0.0.2"
lua = ">=5.1"

[description]
summary = "Build lua rock file by autotools"
detailed = "Make TeX ecosystem available for lua ecosystem"
maintainer = "Wu"
labels = ["texmf"]
homepage = "https://texrocks.readthedocs.io/en/latest/topics/luarocks-build-autotools.md.html"
license = 'GPL-3.0'

[source]
url = "https://github.com/ustctug/texrocks/archive/$(VERSION).zip"
dir = "texrocks-$(VERSION)/packages/$(PACKAGE)"

[dependencies]
luarocks = ">=3.12.2"

[run]
command = "luarocks"

[build]
type = "builtin"
