package = "demo-bib"
version = "0.0.1"
lua = ">=5.1"

[description]
summary = "Example for bib"
maintainer = "Wu"
labels = [ "texmf" ]
license = "GPL-3.0"

[build_dependencies]
lualatex = "0.3.4-1"
citation-style-language = "0.8.0-1"
beamer = "3.72-1"

[test_dependencies]
lua-open = "0.3.4-1"

[test]
type = "command"
command = "lua-open"
flags = ["main.pdf"]

[build]
type = "command"
build_command = "lualatex --interaction=nonstopmode main.tex"

[build.install.conf]
'../doc/main.pdf' = 'main.pdf'
