on:
  push:
    paths-ignore:
      - "**.md"
      - doc/*
  pull_request:
    paths-ignore:
      - "**.md"
      - doc/*
  workflow_dispatch:

# Prevent concurrent auto-commits
concurrency:
  group: auto-commit-linux-x86_64
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.GH_TOKEN}}
          ref: gh-pages
      - name: Install Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.3"
      - name: Install Luarocks
        uses: hishamhm/gh-actions-luarocks@master
      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install rename parallel
      - env:
          LUA_PATH: /home/runner/.luarocks/share/lua/5.3/?.lua
          TEXMFDOTDIR: .;/home/runner/.luarocks//
        run: |
          luarocks install --local luahbtex
          luarocks install --local luatex
          luarocks install --local luatexinfo
          luarocks install --local lualatex
          luarocks install --local texdoc
          luarocks install --local l3build
          luarocks install --local luafindfont
          luarocks list --porcelain | cut -f1 | sed 's/^/luarocks pack /' | sh
          rename -f s/linux-x86_64/all/ \
            {texrocks,luatex{,info},lualatex,texdoc,l3build,luafindfont}-*.rock
          luarocks-admin make-manifest .
          parallel zip manifest-5.{}.zip manifest-5.{} ::: {1..4}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          commit_message: 'chore: update build artifacts'
          file_pattern: index.html manifest* *.rock
          commit_options: --amend --no-edit
          push_options: --force
