---
"on":
  push:
    paths-ignore:
      - "**.md"
      - doc/*
  pull_request:
    paths-ignore:
      - "**.md"
      - doc/*
  workflow_dispatch:

# Prevent concurrent auto-commits
concurrency:
  group: auto-commit-linux-x86_64
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.GH_TOKEN}}
          ref: gh-pages
      - uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.3"
      - uses: hishamhm/gh-actions-luarocks@master
      - name: Install Dependencies
        run: |
          sudo apt-get -y update
          sudo apt-get -y install rename parallel
          # https://github.com/drivendataorg/repro-zipfile/pull/23
          pip install git+https://github.com/Freed-Wu/repro-zipfile@mode rpzip
      - env:
          TEXMFDOTDIR: .;~/.luarocks/lib/luarocks/rocks-5.3//
        run: |
          luarocks config variables.ZIP rpzip
          # luarocks config rocks_servers.1 https://ustctug.github.io/texrocks
          # luarocks config rocks_servers.2 https://luarocks.org
          luarocks install --local luahbtex \
            --server=https://ustctug.github.io/texrocks
          luarocks install --local luatex
          luarocks install --local luatexinfo
          luarocks install --local lualatex
          luarocks install --local citation-style-language
          luarocks install --local texdef
          luarocks install --local graphics-cfg
          luarocks install --local beamer
          luarocks install --local standalone
          luarocks install --local hologo
          luarocks install --local hypdoc
          luarocks install --local ydoc
          rm -f ./*.rock
          luarocks list --porcelain | cut -f1 | sed 's/^/luarocks pack /' | sh
          rename -f s/linux-x86_64/all/ {citation-style-language,texdef,\
          texrocks,luatex{,info},lualatex}-*.rock
          luarocks-admin make-manifest .
          parallel zip manifest-5.{}.zip manifest-5.{} ::: {1..4}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          commit_message: 'chore: update build artifacts'
          file_pattern: index.html manifest* *.rock
          commit_options: --amend --no-edit
          push_options: --force
