---
"on":
  push:
    paths-ignore:
      - "**.md"
      - doc/*
  pull_request:
    paths-ignore:
      - "**.md"
      - doc/*
  workflow_dispatch:

# Prevent concurrent auto-commits
concurrency:
  group: auto-commit-linux-x86_64
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.GH_TOKEN}}
          ref: gh-pages
      - uses: actions/checkout@v4
        with:
          token: ${{secrets.GH_TOKEN}}
          path: texrocks
      - uses: actions/setup-go@v5
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
      - uses: leafo/gh-actions-lua@v12
        with:
          luaVersion: "5.3"
      - uses: luarocks/gh-actions-luarocks@v6
      - name: Install Dependencies
        run: |
          gem install rake
          sudo apt-get -y update
          sudo apt-get -y install rename liblua5.3-dev
      - env:
          TEXMFDOTDIR: .;~/.luarocks/lib/luarocks/rocks-5.3//
          CGO_CFLAGS: -I/home/runner/work/texrocks/texrocks/.lua/include
          CXXFLAGS: -I/home/runner/work/texrocks/texrocks/.lua/include
        run: |
          texrocks/scripts/deploy.sh
          rm -r texrocks
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: gh-pages
          commit_message: 'chore: update build artifacts'
          file_pattern: index.html manifest* *.rock
          commit_options: --amend --no-edit
          push_options: --force
