---
"on":
  push:
    paths-ignore:
      - "**.md"
      - doc/*
  pull_request:
    paths-ignore:
      - "**.md"
      - doc/*
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nvim-neorocks/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{secrets.LUAROCKS_API_KEY}}
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          extra_luarocks_args: |
            --force
          version: scm
          template: template.rockspec
      - uses: lumen-oss/luarocks-tag-release@v7
        env:
          LUAROCKS_API_KEY: ${{secrets.LUAROCKS_API_KEY}}
        if: startsWith(github.ref, 'refs/tags/')
        with:
          extra_luarocks_args: |
            --force
          template: template.rockspec
      - uses: zauguin/install-texlive@v4
        with:
          packages: |
            l3build
      - uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.3"
      - uses: hishamhm/gh-actions-luarocks@master
      - run: |
          luarocks install toml2lua
          scripts/ctan.sh
        env:
          TEXMFDOTDIR: .;~/work/texrocks/texrocks/.luarocks/share/lua/5.3//
      - uses: actions/upload-artifact@v4
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          path: |
            build/distrib/ctan/*-ctan.zip
            build/distrib/tds/*.tds.zip
      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/distrib/ctan/*-ctan.zip
            build/distrib/tds/*.tds.zip
