package = "luatexinfo-build-environment"
version = "0.0.1"
lua = "==5.3"

[description]
summary = "LuaTex for TeXinfo"
maintainer = "Wu Zhenyu"
labels = ["texmf"]
license = "GPL-3.0"

[dependencies]
texrocks = "==0.1.0"
texinfo = "7.2-2"
knuth-lib = "scm-1"
amsfonts = "scm-1"

[run]
command = "texrocks"
args = ["--dump", "luatexinfo"]

[build]
type = "none"
